# version: "2"
services:
  sh_issue_certificate:
    platform: linux/x86_64
    env_file: ".env"
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
     - "10000:10000"
    volumes:
     - ./docker/certificados:/var/www/temp
    environment:
      - "GO_SH_ID=${GO_SH_ID}"
      - "GO_SH_APP=${GO_SH_APP}"
      - "GO_SH_KEY=${GO_SH_KEY}"
      - "GO_SH_HOMOLOGATION=${GO_SH_HOMOLOGATION}"

